CREATE TABLE books (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(2000) NULL,
  author VARCHAR(2000) NULL,
  price DECIMAL(18,2) NOT NULL,
  launch_date DATETIME NOT NULL,
  PRIMARY KEY (id)
);