services:
  rest-with-asp-net-10-erudio:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ooliveir4/rest-with-asp-net-10-erudio:latest
    container_name: rest-api-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__MySQLServerSqlConnectionStrings=Server=${DB_HOST};Port=3306;Database=${DB_NAME};Uid=${DB_USER};Pwd=${DB_PASSWORD};
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - erudio-network
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - erudio-network

networks:
  erudio-network:
    driver: bridge

volumes:
  portainer_data: