name: Continuous Integration, Delivery and Deployment with Github Actions and .NET 10

on:
  push:
    branches: [ "main", "dev" ]

    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Create SQL Server Container
      run: |
        docker run -d --name sqlserver_teste \
          -e "ACCEPT_EULA=Y" \
          -e "MSSQL_SA_PASSWORD=SENHA_REMOVIDA" \
          -p 1433:1433 \
          mcr.microsoft.com/mssql/server:2022-latest

        timeout 90s bash -c "until docker exec sqlserver_teste /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P SENHA_REMOVIDA -Q 'SELECT 1' -C; do sleep 5; done"

    - name: Create SQL Server Database
      run: docker exec sqlserver_teste /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P SENHA_REMOVIDA -Q "IF DB_ID('asp_net_10_erudio') IS NULL CREATE DATABASE asp_net_10_erudio" -C

    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Restore Dependecies
      run: dotnet restore RestWithASPNET10Erudio.csproj
      working-directory: RestWithASPNET10Erudio/RestWithASPNET10Erudio

    - name: Build ASP.NET 10 App
      run: dotnet build RestWithASPNET10Erudio.csproj --configuration Release --no-restore
      working-directory: RestWithASPNET10Erudio/RestWithASPNET10Erudio

    - name: Test ASP.NET 10 App
      run: |
        dotnet build RestWithASPNET10Erudio.Tests.csproj --configuration Release
        dotnet test RestWithASPNET10Erudio.Tests.csproj --configuration Release --no-build --logger "console;verbosity=detailed"
      working-directory: UnitTestsInAPS_NET/RestWithASPNET10Erudio.Tests

    - name: Docker Compose Build
      run: |
        docker compose build
        docker images
      working-directory: RestWithASPNET10Erudio/RestWithASPNET10Erudio

    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.AZ_DOCKER_USERNAME }}
        password: ${{ secrets.AZ_DOCKER_PASSWORD }}
          
    - name: Push Docker Images to Azure Container Registry
      run: |
        docker tag ooliveir4/rest-with-asp-net-10-erudio:latest ${{ secrets.AZURE_CONTAINER_REGISTRY }}/rest-with-asp-net-10-erudio:latest
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/rest-with-asp-net-10-erudio:latest
        docker tag ooliveir4/rest-with-asp-net-10-erudio:latest ${{ secrets.AZURE_CONTAINER_REGISTRY }}/rest-with-asp-net-10-erudio:${{ github.run_id }}
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/rest-with-asp-net-10-erudio:${{ github.run_id }}

    - name: Push to Docker Hub to Container Registry
      run: |
        docker push ooliveir4/rest-with-asp-net-10-erudio:latest
        docker tag ooliveir4/rest-with-asp-net-10-erudio:latest ooliveir4/rest-with-asp-net-10-erudio:${{ github.run_id }}
        docker push ooliveir4/rest-with-asp-net-10-erudio:${{ github.run_id }}